services:
  client:
    container_name: portfolio-web-client-dev
    build:
      context: ../client
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../client:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  server:
    container_name: portfolio-web-server-dev
    build:
      context: ../server
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
